---
name: cmpsc-100-week-00-lab
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"

CMPSC 100 - Week 00 - Lab - The Maltese Python.ipynb:
    ConfirmFileExists
the_maltese_python!:
    ConfirmFileExists
