---
name: cmpsc-100-week-00-worksheets
break: true
indent: 4
---

1 - CMPSC 100 - Week 00 - Worksheet - Configuration.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "cat ~/.ssh/id_rsa.pub" --count 2
2 - CMPSC 100 - Week 00 - Worksheet - Terminal commands.ipynb:
    ConfirmFileExists
3 - CMPSC 100 - Week 00 - Worksheet - Markdown.ipynb:
    ConfirmFileExists